export const SHINGLE_TYPES = { threeTab: { label: "3-tab asphalt shingles", poundsPerSquare: 240 }, architectural: { label: "Architectural asphalt shingles", poundsPerSquare: 420 } } as const;
export const DUMPSTERS = [{ yards: 10, typicalMaxLb: 4000, defaultIncludedTons: 2 },{ yards: 15, typicalMaxLb: 4000, defaultIncludedTons: 2 },{ yards: 20, typicalMaxLb: 6000, defaultIncludedTons: 3 },{ yards: 30, typicalMaxLb: 8000, defaultIncludedTons: 4 },{ yards: 40, typicalMaxLb: 10000, defaultIncludedTons: 5 }];
type Input = { areaUnit:string; area:number; shingleType:string; layers:number; includeUnderlayment:boolean; wastePercent:number; extraDebrisLb:number; quoteDumpsterYards:number; includedTons:number; rentalPrice:number; overagePerTon:number };
const clamp=(v:number,min:number,max:number)=>Math.min(Math.max(v,min),max); const round=(v:number,d=1)=>Number(v.toFixed(d));
export function calculateRoofingEstimate(input:Input){
 const roofSquares=input.areaUnit==="squares"?input.area:input.area/100; const shingle=SHINGLE_TYPES[input.shingleType as keyof typeof SHINGLE_TYPES]??SHINGLE_TYPES.architectural; const layers=clamp(Number(input.layers||1),1,5); const allowance=clamp(Number(input.wastePercent||0),0,50); const base=roofSquares*shingle.poundsPerSquare*layers+(input.includeUnderlayment?roofSquares*15:0)+Math.max(input.extraDebrisLb||0,0); const expectedWeightLb=base*(1+allowance/100); const lowWeightLb=expectedWeightLb*.9, highWeightLb=expectedWeightLb*1.12; const expectedTons=expectedWeightLb/2000, lowTons=lowWeightLb/2000, highTons=highWeightLb/2000; const lowVolumeYd3=lowTons/.37, expectedVolumeYd3=expectedTons/.29, highVolumeYd3=highTons/.21; const volumeDumpster=DUMPSTERS.find(d=>d.yards>=highVolumeYd3); const weightDumpster=DUMPSTERS.find(d=>d.typicalMaxLb>=highWeightLb); let recommendation:{yards:number|null;label:string;reason:string;typicalMaxLb?:number;defaultIncludedTons?:number};
 if(!volumeDumpster||!weightDumpster) recommendation={yards:null,label:"Multiple hauls or a custom heavy-material container",reason:!weightDumpster?"weight":"volume"}; else {const vi=DUMPSTERS.indexOf(volumeDumpster),wi=DUMPSTERS.indexOf(weightDumpster),selected=DUMPSTERS[Math.max(vi,wi)];recommendation={...selected,label:`${selected.yards}-yard dumpster`,reason:wi>vi?"weight":vi>wi?"volume":"both"};}
 const quote=DUMPSTERS.find(d=>d.yards===Number(input.quoteDumpsterYards))??DUMPSTERS[2]; const included=Math.max(input.includedTons??quote.defaultIncludedTons,0), rate=Math.max(input.overagePerTon||0,0), rental=Math.max(input.rentalPrice||0,0), expectedExcess=Math.max(0,expectedTons-included), highExcess=Math.max(0,highTons-included);
 return {roofSquares:round(roofSquares,2),roofAreaSqFt:round(roofSquares*100,0),shingleLabel:shingle.label,expectedWeightLb:round(expectedWeightLb,0),lowTons:round(lowTons,2),expectedTons:round(expectedTons,2),highTons:round(highTons,2),lowVolumeYd3:round(lowVolumeYd3,1),expectedVolumeYd3:round(expectedVolumeYd3,1),highVolumeYd3:round(highVolumeYd3,1),recommendation,quote:{dumpsterYards:quote.yards,includedTons:round(included,2),expectedExcessTons:round(expectedExcess,2),highExcessTons:round(highExcess,2),expectedOverage:round(expectedExcess*rate,2),expectedTotal:round(rental+expectedExcess*rate,2),volumeUsagePct:round(expectedVolumeYd3/quote.yards*100,0),weightUsagePct:included>0?round(expectedTons/included*100,0):0}};
}
