import Link from "next/link";
import {Footer,Header} from "./components";
import {categories,projects} from "./project-data";

export default function Home(){return <><Header/><main>
  <section className="home-hero"><div><span className="eyebrow">Plan before you hire</span><h1>Know the numbers behind your next home project.</h1><p>Free, transparent US cost calculators with realistic ranges, clear assumptions, contractor quote comparison, and printable project briefs.</p><a className="primary-link" href="#calculators">Explore 15 calculators</a><div className="trust-row"><span>No signup</span><span>Printable estimates</span><span>Transparent methodology</span></div></div><aside><span className="mini-label">A better starting point</span><strong>Not one magic number.</strong><p>See a defensible low-to-high range, what drives it, and what to ask before signing a quote.</p><div className="hero-range"><span>Low</span><i/><span>Typical</span><i/><span>High</span></div></aside></section>
  <section className="proof-strip"><div><strong>15</strong><span>project planners</span></div><div><strong>5</strong><span>cost regions</span></div><div><strong>3</strong><span>finish levels</span></div><div><strong>1-click</strong><span>print or PDF</span></div></section>
  <section id="calculators" className="catalog"><div className="section-heading"><span className="eyebrow">Calculator library</span><h2>Start with the project you are planning.</h2><p>Each tool uses project-specific cost ranges with the same consistent planning and quote-review workflow.</p></div>
  {categories.map(category=><section className="category" key={category}><div className="category-title"><h3>{category}</h3><span>{projects.filter(p=>p.category===category).length} tools</span></div><div className="tool-grid">{projects.filter(p=>p.category===category).map(p=><Link className="tool-card" href={`/calculators/${p.slug}`} key={p.slug}><span className="tool-icon">{p.icon}</span><div><h4>{p.title}</h4><p>{p.description}</p><span className="card-link">Build an estimate →</span></div></Link>)}</div></section>)}
  <section className="category"><div className="category-title"><h3>Project logistics</h3><span>1 specialist tool</span></div><div className="tool-grid"><Link className="tool-card feature-tool" href="/roofing-debris"><span className="tool-icon">DB</span><div><h4>Roofing Debris & Dumpster</h4><p>Estimate tear-off weight, loose volume, dumpster size, and potential overweight charges.</p><span className="card-link">Plan the load →</span></div></Link></div></section>
  </section>
  <section className="launch-value"><div><span className="eyebrow">Useful after the estimate</span><h2>Take a project brief into every contractor conversation.</h2></div><div><p>Print your inputs, cost range, breakdown, assumptions, and questions. Add contractor quotes and compare them against the same scope.</p><ul><li>Low, typical, and high planning range</li><li>Material, labor, permit, and contingency split</li><li>Editable quote comparison</li><li>Print or save as PDF—no account required</li></ul></div></section>
 </main><Footer/></>}
